### PR TITLE
Update for some deprecation warnings

### PR DESCRIPTION
**Pull request by aaa707**
Hi rc-switch committers,

I have updated this library for some deprecation warnings.
rc-swich is written in without es6, so I think it's a temporaly fix.
But could you merge this?

Thanks,

### CODE REVIEW

**Comment by paranoidjk** [comment]
would you like to rewrite it in es6 class ?

**Comment by aaa707** [comment]
Hi @paranoidjk 

IMO, it should be rewritten in es6 in the future because most of components under react-componet are written in es6. But it's ok right now. 😄

**Comment by paranoidjk** [comment]
@aaa707 It would be great if you can help us rewrite it in es6 class, since createClass is deprecated，we need a long term solution, not a temporary  workaround.

**Comment by afc163** [comment]
fixed in #11

**Pull request closed without merging**
